apiVersion: apps/v1
kind: Deployment
metadata:
  name: moses-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moses-api
  template:
    metadata:
      labels:
        app: moses-api
    spec:
      containers:
        - name: moses-api
          image: gcr.io/my-devops-team/moses-api:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: 3000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 10